'use strict';
/* Shared content for detail pages only. Never imported by the home solar-system canvas. */
const PLANET_DATA = {};
const epFacts = (diameter, orbit, moons, temperature) => [
  { icon:'D', value:diameter, label:'Đường kính' },
  { icon:'O', value:orbit, label:'Chu kỳ quỹ đạo' },
  { icon:'M', value:moons, label:'Vệ tinh' },
  { icon:'T', value:temperature, label:'Nhiệt độ' }
];
const epSigns = (physical, thoughts, behaviors, social) => ({
  physical: physical.map(([title,detail]) => ({title,detail})),
  thoughts: thoughts.map(([title,detail]) => ({title,detail})),
  behaviors: behaviors.map(([title,detail]) => ({title,detail})),
  social: social.map(([title,detail]) => ({title,detail}))
});
const epLoop = (items, interventionPoint, interventionLabel) => ({
  trigger:{title:'Tác nhân',example:items[0]}, bodyResponse:{title:'Phản ứng cơ thể',example:items[1]},
  autoThought:{title:'Suy nghĩ tự động',example:items[2]}, behavior:{title:'Hành vi',example:items[3]},
  shortTerm:{title:'Hệ quả ngắn hạn',example:items[4]}, longTerm:{title:'Hệ quả dài hạn',example:items[5]},
  interventionPoint, interventionLabel
});

PLANET_DATA.mercury = {
  id:'mercury', name:'Sao Thủy', nameEn:'Mercury', emotion:'Cô đơn', emotionEn:'Loneliness', texture:'mercury.png',
  tagline:'Khoảng lặng không phải là kết thúc kết nối; đôi khi đó là tín hiệu cho biết ta đang cần được nhìn thấy.',
  facts:epFacts('4.879 km','88 ngày','0','-180–430°C'),
  connection:{
    planetTraits:['Nhỏ nhất và gần Mặt Trời nhất','Không có vệ tinh đồng hành','Bề mặt khắc đầy dấu va chạm'],
    emotionTraits:['Cảm giác tách khỏi người khác','Thiếu sự đồng điệu hơn là thiếu người','Nhạy với dấu hiệu bị bỏ quên'],
    analogy:'Sao Thủy ở rất gần nguồn sáng nhưng vẫn là một thế giới không có mặt trăng. Cô đơn cũng có thể xuất hiện giữa đám đông: khoảng cách cảm xúc quan trọng hơn khoảng cách vật lý.',
    quote:{text:'Cô đơn là tín hiệu về nhu cầu kết nối, không phải bằng chứng rằng bạn không đáng được yêu thương.',author:'StellarMind'}
  },
  overview:{
    what:'Cô đơn là cảm nhận chủ quan rằng các mối quan hệ hiện tại chưa đáp ứng mức kết nối ta cần. Một người có thể ở một mình mà bình an, hoặc ở giữa nhiều người nhưng vẫn cô độc.',
    why:'Con người tiến hóa trong cộng đồng. Cảm giác cô đơn hoạt động như tín hiệu thúc đẩy ta tìm lại sự an toàn, thuộc về và trao đổi cảm xúc.',
    whenNormal:'Nó thường xuất hiện khi chuyển trường, chuyển việc, mất một mối quan hệ hoặc khi nhu cầu kết nối thay đổi. Tín hiệu này có thể giúp ta chủ động xây dựng quan hệ phù hợp hơn.',
    whenHarmful:'Khi kéo dài, làm bạn rút lui thêm, mất ngủ, suy giảm sinh hoạt hoặc cảm thấy tuyệt vọng, hãy tìm người đáng tin hay chuyên gia để được hỗ trợ.',
    misconceptions:['Cô đơn không đồng nghĩa với yếu đuối hay kém hấp dẫn.','Nhiều tương tác trực tuyến không tự động tạo ra cảm giác được thấu hiểu.']
  },
  signs:epSigns(
    [['Ngực trống rỗng','Cảm giác hụt hoặc nặng ở giữa ngực.'],['Giấc ngủ chập chờn','Khó thư giãn dù cơ thể đã mệt.'],['Năng lượng thấp','Bắt đầu một cuộc trò chuyện cũng trở nên nặng nề.']],
    [['“Không ai hiểu mình”','Tâm trí lọc mạnh dấu hiệu bị bỏ quên.'],['Đọc ý người khác','Dễ kết luận im lặng là từ chối.'],['So sánh kết nối','Đời sống xã hội của người khác trở thành thước đo bản thân.']],
    [['Thu mình','Từ chối lời mời để tránh cảm giác lạc lõng.'],['Lướt mạng kéo dài','Tìm gần gũi nhưng không thực sự tương tác.'],['Chờ người khác mở lời','Sợ chủ động sẽ bị xem là làm phiền.']],
    [['Ít chia sẻ thật','Cuộc trò chuyện chỉ dừng ở bề mặt.'],['Mất nhịp liên lạc','Hai bên đều chờ nhau.'],['Cảm giác ngoài lề','Khó tin mình có vị trí trong nhóm.']]
  ),
  bodyMap:[{x:50,y:25,label:'Đầu nặng vì suy nghĩ lặp lại',size:'md'},{x:50,y:43,label:'Khoảng trống hoặc sức nặng ở ngực',size:'lg'},{x:39,y:63,label:'Tay ít muốn vươn ra kết nối',size:'sm'},{x:50,y:82,label:'Cơ thể chậm và thiếu năng lượng',size:'md'}],
  emotionalLoop:epLoop(['Nhìn thấy nhóm bạn đi chơi mà không có mình.','Ngực hụt, vai co, năng lượng giảm.','“Mình không quan trọng với ai cả.”','Tắt điện thoại và không trả lời tin nhắn.','Tránh được nguy cơ bị từ chối.','Ít cơ hội kết nối, niềm tin cô độc mạnh hơn.'],3,'Thử một kết nối nhỏ, ít rủi ro'),
  research:[
    {org:'WHO',title:'Kết nối xã hội là một nhu cầu sức khỏe',summary:'WHO mô tả cô đơn là khoảng cách giữa kết nối ta có và kết nối ta mong muốn; chất lượng quan hệ quan trọng hơn số lượng.',url:'https://www.who.int/news-room/questions-and-answers/item/social-connection',source:'WHO · Social connection'},
    {org:'HHS',title:'Kết nối và sức khỏe cộng đồng',summary:'Khuyến nghị tập trung vào quan hệ có ý nghĩa, sự hiện diện và những hành động kết nối nhỏ nhưng đều đặn.',url:'https://www.hhs.gov/surgeongeneral/priorities/connection/index.html',source:'U.S. Surgeon General'}
  ],
  scenarios:[
    {icon:'01',context:'Đại học',situation:'Bạn vào lớp mới và thấy mọi người đã có nhóm.',autoThought:'“Mình không hợp với ai ở đây.”',physicalResponse:'Vai co, mắt tránh giao tiếp.',typicalReaction:'Ngồi riêng và rời lớp thật nhanh.',healthierAlternative:'Hỏi một bạn về bài tập hoặc ngồi cùng khu vực trong ba buổi để tạo sự quen thuộc.'},
    {icon:'02',context:'Mạng xã hội',situation:'Cuối tuần chỉ thấy ảnh người khác tụ họp.',autoThought:'“Ai cũng có cuộc sống tốt hơn mình.”',physicalResponse:'Ngực trống, tay lướt không dừng.',typicalReaction:'Tiếp tục xem và không trả lời người đang nhắn.',healthierAlternative:'Đặt điện thoại xuống 10 phút và gửi một lời hỏi thăm cụ thể cho người mình tin.'}
  ],
  practice:{type:'connection',title:'Thang kết nối ba nấc',description:'Chọn mức tiếp xúc vừa sức thay vì ép mình phải lập tức có một cuộc trò chuyện sâu.',steps:[{label:'Hiện diện',instruction:'Ở gần con người trong không gian an toàn.'},{label:'Gửi tín hiệu',instruction:'Chào, phản hồi hoặc hỏi một câu ngắn.'},{label:'Chia sẻ',instruction:'Nói một điều thật nhưng vừa sức.'}]}
};

PLANET_DATA.venus = {
  id:'venus',name:'Sao Kim',nameEn:'Venus',emotion:'Yêu thương',emotionEn:'Love',texture:'venus.png',
  tagline:'Yêu thương là hơi ấm có ranh giới: đủ gần để nâng đỡ, đủ rõ để cả hai vẫn là chính mình.',facts:epFacts('12.104 km','225 ngày','0','≈464°C'),
  connection:{planetTraits:['Hành tinh sáng nổi bật trên bầu trời','Khí quyển dày giữ nhiệt mạnh','Kích thước gần với Trái Đất'],emotionTraits:['Tạo cảm giác ấm áp và thuộc về','Có thể mãnh liệt, cần ranh giới','Phát triển qua sự gần gũi và đáp lại'],analogy:'Sao Kim rực sáng và giữ nhiệt rất mạnh. Tình yêu cũng tạo hơi ấm kết nối, nhưng nếu thiếu ranh giới và khoảng thở, sự gần gũi có thể trở thành áp lực.',quote:{text:'Yêu thương là nhìn thấy người khác rõ hơn mà không làm mờ chính mình.',author:'StellarMind'}},
  overview:{what:'Yêu thương gồm sự quan tâm, gắn bó, tôn trọng và mong điều tốt cho bản thân hoặc người khác. Nó hiện diện trong tình yêu đôi lứa, gia đình, tình bạn và lòng trắc ẩn.',why:'Gắn bó giúp con người hợp tác, chăm sóc và tạo cảm giác an toàn. Sự đáp lại ổn định làm hệ thần kinh dễ bình tĩnh và tăng niềm tin trong quan hệ.',whenNormal:'Tình yêu lành mạnh cho phép gần gũi lẫn độc lập, có thể nói “không”, sửa chữa sau xung đột và không đòi hỏi hoàn hảo.',whenHarmful:'Cần chú ý khi tình yêu bị đồng nhất với kiểm soát, hy sinh liên tục, sợ hãi, cô lập hoặc phải bỏ qua an toàn và nhu cầu của mình.',misconceptions:['Ranh giới không làm tình yêu yếu đi; nó giúp quan hệ rõ ràng và bền hơn.','Yêu ai đó không có nghĩa là phải chịu mọi hành vi của họ.']},
  signs:epSigns(
    [['Cơ thể ấm và mở','Vai thả lỏng, giọng mềm hơn khi cảm thấy an toàn.'],['Muốn tiến gần','Ánh mắt và cơ thể hướng về người quan trọng.'],['Nhạy với chia xa','Có thể bồn chồn khi liên hệ bị gián đoạn.']],
    [['Quan tâm góc nhìn khác','Muốn hiểu thay vì chỉ muốn thắng.'],['Lý tưởng hóa','Đôi lúc bỏ qua dữ kiện không phù hợp kỳ vọng.'],['Sợ mất kết nối','Im lặng nhỏ có thể bị hiểu thành xa cách.']],
    [['Chăm sóc','Chủ động dành thời gian và nguồn lực.'],['Tìm sự gần gũi','Muốn chia sẻ trải nghiệm và nhận phản hồi.'],['Thương lượng ranh giới','Nói rõ điều mình có thể và không thể làm.']],
    [['Tin cậy hai chiều','Có thể nhờ giúp và cũng có thể từ chối.'],['Sửa chữa xung đột','Quay lại cuộc trò chuyện sau khi bình tĩnh.'],['Duy trì bản sắc','Mỗi người vẫn có bạn bè, sở thích và mục tiêu riêng.']]
  ),
  bodyMap:[{x:50,y:27,label:'Ánh mắt và nét mặt mềm hơn',size:'sm'},{x:50,y:43,label:'Ngực ấm hoặc rung động',size:'lg'},{x:37,y:58,label:'Tay muốn chạm hoặc chăm sóc',size:'md'},{x:50,y:67,label:'Bụng bồn chồn khi sợ mất kết nối',size:'md'}],
  emotionalLoop:epLoop(['Người quan trọng trả lời chậm hơn thường lệ.','Bụng căng, tim nhanh, mắt liên tục kiểm tra máy.','“Họ đang chán mình.”','Nhắn dồn hoặc im lặng để thử lòng.','Có cảm giác mình đang kiểm soát tình hình.','Quan hệ căng, niềm tin giảm và nhu cầu khó được nói rõ.'],2,'Kiểm tra dữ kiện và nói nhu cầu không buộc tội'),
  research:[{org:'APA',title:'Quan hệ lành mạnh cần giao tiếp và ranh giới',summary:'Giao tiếp rõ, tôn trọng và khả năng giải quyết bất đồng là thành phần quan trọng của quan hệ an toàn.',url:'https://www.apa.org/topics/relationships',source:'APA · Relationships'},{org:'PubMed',title:'Lòng trắc ẩn với bản thân',summary:'Các tổng quan liên hệ self-compassion với mức đau khổ tâm lý thấp hơn, nhưng đây không thay thế điều trị.',url:'https://pubmed.ncbi.nlm.nih.gov/34955971/',source:'PubMed · Meta-analysis'}],
  scenarios:[{icon:'01',context:'Mối quan hệ',situation:'Đối phương hủy hẹn vì công việc.',autoThought:'“Mình không còn quan trọng.”',physicalResponse:'Bụng thắt, cổ họng nghẹn.',typicalReaction:'Châm chọc hoặc rút lui để họ tự hiểu.',healthierAlternative:'Nói tác động cụ thể, hỏi lịch mới và xác định điều mình cần để cảm thấy được tôn trọng.'},{icon:'02',context:'Gia đình',situation:'Bạn được nhờ giúp dù lịch đã kín.',autoThought:'“Từ chối nghĩa là mình ích kỷ.”',physicalResponse:'Vai căng, thở ngắn.',typicalReaction:'Đồng ý rồi bực bội.',healthierAlternative:'Thể hiện quan tâm và đề nghị một mức hỗ trợ thực tế, có giới hạn thời gian.'}],
  practice:{type:'compassion',title:'Quỹ đạo yêu thương có ranh giới',description:'Đặt một hành động tử tế vào đúng quỹ đạo: người nhận, khả năng của bạn và ranh giới an toàn.',steps:[{label:'Chọn người nhận',instruction:'Có thể là chính bạn.'},{label:'Chọn hành động',instruction:'Nhỏ, cụ thể, làm được trong 15 phút.'},{label:'Kiểm tra ranh giới',instruction:'Đảm bảo hành động đến từ lựa chọn, không phải sợ hãi.'}]}
};

PLANET_DATA.earth = {
  id:'earth',name:'Trái Đất',nameEn:'Earth',emotion:'Lo âu',emotionEn:'Anxiety',texture:'earth.jpg',
  tagline:'Lo âu kéo tâm trí vào những quỹ đạo tương lai; tiếp đất đưa cơ thể trở lại nơi bạn đang đứng.',facts:epFacts('12.756 km','365,25 ngày','1','≈15°C'),
  connection:{planetTraits:['Hệ sống phức tạp và luôn biến đổi','Khí quyển bảo vệ nhưng thời tiết khó đoán','Mọi hệ thống liên kết với nhau'],emotionTraits:['Quét môi trường để tìm nguy cơ','Mô phỏng nhiều kịch bản tương lai','Kích hoạt cơ thể trước khi nguy hiểm xảy ra'],analogy:'Trái Đất là một hệ sống liên tục đọc tín hiệu và điều chỉnh. Lo âu cũng là hệ cảnh báo hữu ích; vấn đề xuất hiện khi chuông báo quá nhạy và mọi đám mây đều bị xem như bão.',quote:{text:'Bạn không cần giải quyết toàn bộ tương lai để chăm sóc phút hiện tại.',author:'StellarMind'}},
  overview:{what:'Lo âu là trạng thái cảnh giác trước nguy cơ có thể xảy ra. Nó kết hợp suy nghĩ dự đoán, cảm giác cơ thể và thôi thúc kiểm soát hoặc né tránh.',why:'Hệ cảnh báo giúp con người chuẩn bị, chú ý và phản ứng nhanh. Não thường ưu tiên khả năng nguy hiểm vì bỏ sót mối đe dọa từng có giá cao trong tiến hóa.',whenNormal:'Lo trước kỳ thi, phỏng vấn hoặc thay đổi lớn có thể giúp ta chuẩn bị. Mức lo vừa phải thường giảm khi sự kiện qua đi hoặc khi có thêm thông tin.',whenHarmful:'Nên tìm hỗ trợ khi lo âu kéo dài, khó kiểm soát, gây cơn hoảng, mất ngủ, né tránh hoặc cản trở học tập, công việc và quan hệ.',misconceptions:['Lo âu không chỉ là “nghĩ quá nhiều”; cơ thể cũng thật sự được kích hoạt.','Bảo một người “đừng lo nữa” thường không đủ để hệ thần kinh bình tĩnh.']},
  signs:epSigns(
    [['Tim nhanh','Cơ thể chuẩn bị hành động dù nguy cơ chưa xảy ra.'],['Thở nông','Ngực căng và khó lấy hơi sâu.'],['Dạ dày khó chịu','Buồn nôn, thắt bụng hoặc muốn đi vệ sinh.']],
    [['Kịch bản “nếu như”','Tâm trí chạy qua nhiều kết quả xấu.'],['Đòi hỏi chắc chắn','Khó hành động khi chưa biết mọi chi tiết.'],['Phóng đại hậu quả','Một lỗi nhỏ bị xem như thảm họa.']],
    [['Né tránh','Trì hoãn tình huống làm mình lo.'],['Kiểm tra lặp lại','Đọc lại, hỏi lại hoặc tìm bảo đảm.'],['Chuẩn bị quá mức','Dành quá nhiều thời gian để loại bỏ mọi rủi ro.']],
    [['Tìm trấn an','Liên tục hỏi người khác liệu mọi thứ có ổn.'],['Khó hiện diện','Ở cùng người khác nhưng đầu óc ở tương lai.'],['Thu hẹp đời sống','Bỏ dần hoạt động vì sợ cảm giác lo.']]
  ),
  bodyMap:[{x:50,y:25,label:'Đầu chạy nhanh với các kịch bản tương lai',size:'lg'},{x:50,y:42,label:'Tim nhanh và thở nông',size:'lg'},{x:50,y:62,label:'Dạ dày thắt hoặc buồn nôn',size:'md'},{x:42,y:78,label:'Chân bồn chồn, muốn tránh đi',size:'sm'}],
  emotionalLoop:epLoop(['Nhận email: “Mai chúng ta cần nói chuyện.”','Tim nhanh, tay lạnh, bụng thắt.','“Chắc mình đã làm sai điều nghiêm trọng.”','Đọc lại mọi việc, hỏi nhiều người để được trấn an.','Dịu đi vài phút nhờ có lời bảo đảm.','Não học rằng không thể chịu được sự không chắc chắn.'],1,'Tiếp đất trước khi phân tích'),
  research:[{org:'NIMH',title:'Lo âu khác với lo lắng nhất thời',summary:'NIMH mô tả rối loạn lo âu là tình trạng lo sợ không biến mất và có thể nặng dần, ảnh hưởng hoạt động hằng ngày.',url:'https://www.nimh.nih.gov/health/topics/anxiety-disorders',source:'NIMH · Anxiety Disorders'},{org:'NHS',title:'Grounding và điều hòa nhịp thở',summary:'Đưa chú ý về giác quan và thở chậm có thể hỗ trợ giảm kích hoạt trong thời điểm căng thẳng.',url:'https://www.nhsinform.scot/healthy-living/mental-wellbeing/stress/breathing-and-relaxation-exercises-for-stress/',source:'NHS inform · Breathing'}],
  scenarios:[{icon:'01',context:'Trường học',situation:'Ngày mai thuyết trình trước lớp.',autoThought:'“Mình sẽ đứng hình và mọi người cười.”',physicalResponse:'Tim nhanh, tay ướt.',typicalReaction:'Xin nghỉ hoặc chuẩn bị đến kiệt sức.',healthierAlternative:'Tập một lần có giới hạn, dùng 5–4–3–2–1 và chấp nhận một mức run vừa phải.'},{icon:'02',context:'Công việc',situation:'Quản lý chưa phản hồi bản đề xuất.',autoThought:'“Im lặng nghĩa là họ không hài lòng.”',physicalResponse:'Bụng căng, liên tục mở email.',typicalReaction:'Gửi nhiều tin nhắn hoặc không làm việc khác được.',healthierAlternative:'Đặt thời điểm kiểm tra lại, ghi ba khả năng trung tính và quay về việc trong tầm kiểm soát.'}],
  practice:{type:'grounding',title:'Trạm tiếp đất 5–4–3–2–1',description:'Dùng năm giác quan để chuyển chú ý khỏi dự đoán tương lai về dữ kiện đang có trong hiện tại.',steps:[{label:'Quan sát',instruction:'Gọi tên thứ bạn thật sự nhìn, chạm, nghe và ngửi.'},{label:'Thở chậm',instruction:'Thở ra dài hơn hít vào, không cố lấy hơi quá sâu.'},{label:'Chọn bước nhỏ',instruction:'Làm một việc trong tầm kiểm soát ngay bây giờ.'}]}
};

PLANET_DATA.mars = {
  id:'mars',name:'Sao Hỏa',nameEn:'Mars',emotion:'Giận dữ',emotionEn:'Anger',texture:'mars.png',
  tagline:'Giận dữ mang năng lượng bảo vệ; khoảng dừng quyết định năng lượng ấy trở thành ranh giới hay vết thương.',facts:epFacts('6.779 km','687 ngày','2','≈-63°C'),
  connection:{planetTraits:['Bề mặt đỏ do oxit sắt','Dấu vết núi lửa và địa hình cực đoan','Bão bụi có thể bao phủ diện rộng'],emotionTraits:['Tăng năng lượng để bảo vệ ranh giới','Nóng nhanh khi thấy bất công','Có thể che cảm xúc dễ tổn thương hơn'],analogy:'Màu đỏ và những cơn bão bụi khiến Sao Hỏa thành hình ảnh của năng lượng mạnh. Giận dữ cũng che kín tầm nhìn khi lên cao, nhưng thường đang báo một ranh giới, nhu cầu hoặc giá trị bị xâm phạm.',quote:{text:'Cơn giận là người đưa tin; đừng để người đưa tin cầm lái.',author:'StellarMind'}},
  overview:{what:'Giận dữ là phản ứng trước bất công, cản trở, xúc phạm hoặc đe dọa. Nó tạo năng lượng để đối đầu và bảo vệ điều quan trọng.',why:'Cơ thể tăng nhịp tim, căng cơ và tập trung vào mối đe dọa để hành động nhanh. Cơn giận có thể giúp ta nhận ra điều không chấp nhận được.',whenNormal:'Giận là bình thường khi ranh giới bị vi phạm. Khi được điều chỉnh, nó giúp nói rõ nhu cầu, giải quyết vấn đề và tạo thay đổi.',whenHarmful:'Cần hỗ trợ khi cơn giận dẫn đến đe dọa, bạo lực, phá hoại, mất kiểm soát, dùng chất hoặc gây sợ hãi cho bản thân và người khác.',misconceptions:['Cảm thấy giận không đồng nghĩa với hành xử hung hăng.','Kìm nén hoàn toàn không phải điều chỉnh; cảm xúc cần được nhận biết và diễn đạt an toàn.']},
  signs:epSigns(
    [['Nhiệt tăng','Mặt nóng, tim nhanh, mồ hôi.'],['Cơ siết','Hàm, vai và nắm tay căng.'],['Tầm nhìn hẹp','Khó tiếp nhận thông tin không khớp cơn giận.']],
    [['Ngôn ngữ tuyệt đối','“Luôn luôn”, “không bao giờ”, “phải”.'],['Gán ý định','Kết luận người khác cố tình làm tổn thương.'],['Tập trung bất công','Tâm trí phát lại chi tiết bị xúc phạm.']],
    [['Nói lớn hoặc nhanh','Muốn áp đảo để được nghe.'],['Cắt lời','Khó chờ khi cơ thể ở chế độ chiến đấu.'],['Bỏ đi đột ngột','Rút khỏi tình huống nhưng không hẹn quay lại.']],
    [['Người khác phòng thủ','Nhu cầu bị che bởi cách truyền đạt.'],['Xung đột leo thang','Mỗi bên đáp lại cường độ của bên kia.'],['Hối tiếc sau đó','Quan hệ phải sửa hậu quả của phút bốc đồng.']]
  ),
  bodyMap:[{x:50,y:25,label:'Mặt nóng, hàm siết',size:'lg'},{x:50,y:42,label:'Tim đập mạnh và ngực căng',size:'lg'},{x:34,y:60,label:'Nắm tay hoặc cánh tay siết',size:'md'},{x:50,y:78,label:'Chân sẵn sàng tiến tới hoặc bỏ đi',size:'md'}],
  emotionalLoop:epLoop(['Đồng nghiệp nhận công cho phần việc của bạn.','Mặt nóng, hàm siết, tim đập mạnh.','“Họ coi thường mình và phải bị vạch mặt ngay.”','Phản bác gay gắt trước cả nhóm.','Giải phóng năng lượng và cảm thấy mạnh hơn.','Thông điệp bị mất, quan hệ và uy tín bị tổn thương.'],1,'Hạ nhiệt cơ thể trong 90 giây'),
  research:[{org:'APA',title:'Giận dữ là cảm xúc bình thường',summary:'APA phân biệt cảm xúc giận với cách biểu đạt; quản lý cơn giận tập trung vào nhận diện kích hoạt và phản ứng xây dựng.',url:'https://www.apa.org/topics/anger/control',source:'APA · Controlling anger'},{org:'NHS',title:'Nhận biết dấu hiệu sớm',summary:'Nhận ra tim nhanh, cơ căng và thôi thúc hành động sớm tạo cơ hội tạm dừng trước khi xung đột leo thang.',url:'https://www.nhs.uk/mental-health/feelings-symptoms-behaviours/feelings-and-symptoms/anger/',source:'NHS · Anger'}],
  scenarios:[{icon:'01',context:'Công việc',situation:'Ý tưởng của bạn bị ngắt lời trong cuộc họp.',autoThought:'“Không ai tôn trọng mình.”',physicalResponse:'Mặt nóng, giọng cao.',typicalReaction:'Cắt lại lời người khác và công kích.',healthierAlternative:'Ghi nhận cơn nóng, xin lại lượt nói và nói: “Tôi muốn hoàn tất ý này trước khi nhận phản hồi.”'},{icon:'02',context:'Gia đình',situation:'Người thân tiếp tục dùng đồ của bạn không hỏi.',autoThought:'“Họ cố tình phớt lờ mình.”',physicalResponse:'Hàm siết, tay căng.',typicalReaction:'Quát và nhắc lại mọi lỗi cũ.',healthierAlternative:'Tạm dừng rồi nói: “Tôi thấy bực khi đồ bị dùng không hỏi; tôi cần bạn xin phép trước.”'}],
  practice:{type:'cooldown',title:'Buồng hạ nhiệt 90 giây',description:'Tạo khoảng dừng cho cơ thể giảm kích hoạt, sau đó chuyển cơn giận thành câu nói có cảm xúc, tình huống và nhu cầu.',duration:90,steps:[{label:'Tách khỏi tia lửa',instruction:'Tạm dừng phản hồi và báo rằng bạn sẽ quay lại.'},{label:'Hạ nhiệt',instruction:'Thả hàm, bàn tay và kéo dài nhịp thở ra.'},{label:'Nói nhu cầu',instruction:'Dùng cấu trúc “Tôi cảm thấy… khi… tôi cần…”.'}]}
};

PLANET_DATA.jupiter = {
  id:'jupiter',name:'Sao Mộc',nameEn:'Jupiter',emotion:'Áp lực',emotionEn:'Pressure',texture:'jupiter.png',
  tagline:'Không phải mọi vật thể đi qua đều phải bị hút vào quỹ đạo của bạn.',facts:epFacts('139.822 km','≈12 năm','95','≈-110°C'),
  connection:{planetTraits:['Hành tinh lớn nhất hệ Mặt Trời','Trọng lực mạnh và nhiều vệ tinh','Đại Hồng Ban là cơn bão lâu dài'],emotionTraits:['Cảm giác phải chứa quá nhiều trách nhiệm','Mọi việc đều có vẻ quan trọng và khẩn cấp','Căng thẳng kéo dài dù vẫn hoạt động'],analogy:'Sao Mộc có trường hấp dẫn khổng lồ và một hệ vệ tinh đông đúc. Áp lực cũng khiến ta kéo mọi nhiệm vụ, kỳ vọng và vấn đề vào cùng một quỹ đạo, đến mức không còn thấy giới hạn năng lượng.',quote:{text:'Ưu tiên không phải làm ít giá trị hơn; đó là bảo vệ năng lượng cho điều thật sự quan trọng.',author:'StellarMind'}},
  overview:{what:'Áp lực là cảm giác yêu cầu đang vượt hoặc tiến sát nguồn lực ta có: thời gian, năng lượng, kỹ năng và sự hỗ trợ.',why:'Phản ứng stress giúp huy động năng lượng trong ngắn hạn. Nó hữu ích khi cần tập trung, nhưng cơ thể không được thiết kế để duy trì cảnh báo cao liên tục.',whenNormal:'Một đợt áp lực ngắn trước hạn chót có thể tăng tập trung nếu khối lượng rõ ràng và có thời gian phục hồi.',whenHarmful:'Áp lực kéo dài, mất ngủ, kiệt sức, đau đầu, cáu gắt hoặc không còn khả năng hồi phục là dấu hiệu cần giảm tải và tìm hỗ trợ.',misconceptions:['Bận rộn không phải thước đo duy nhất của năng lực hay giá trị.','Nghỉ ngơi là một phần của hiệu suất bền vững, không phải phần thưởng sau kiệt sức.']},
  signs:epSigns(
    [['Vai và cổ căng','Cơ thể giữ tư thế sẵn sàng kéo dài.'],['Đau đầu','Căng cơ, thiếu ngủ và màn hình có thể góp phần.'],['Khó hồi phục','Đã nghỉ nhưng đầu óc vẫn chạy danh sách việc.']],
    [['Mọi thứ đều khẩn','Khó phân biệt việc quan trọng và việc chỉ gây ồn.'],['“Mình phải tự làm”','Ngại giao việc hoặc xin hỗ trợ.'],['Giá trị gắn thành tích','Một ngày ít năng suất bị xem là thất bại.']],
    [['Đa nhiệm liên tục','Đổi việc nhanh nhưng ít việc hoàn thành sâu.'],['Bỏ nghỉ','Ăn vội, ngủ muộn và không có khoảng chuyển.'],['Trì hoãn vì quá tải','Khối lượng lớn khiến khó chọn điểm bắt đầu.']],
    [['Khó nhờ giúp','Sợ bị đánh giá kém năng lực.'],['Cáu với người gần','Hệ thần kinh không còn dư địa cho gián đoạn.'],['Thu hẹp đời sống','Chỉ còn công việc và nghĩa vụ.']]
  ),
  bodyMap:[{x:50,y:28,label:'Đầu nén bởi danh sách việc',size:'lg'},{x:44,y:39,label:'Cổ và vai giữ căng',size:'lg'},{x:50,y:58,label:'Dạ dày thất thường khi ăn vội',size:'md'},{x:50,y:80,label:'Toàn thân mệt nhưng khó dừng',size:'md'}],
  emotionalLoop:epLoop(['Ba hạn chót rơi vào cùng một tuần.','Vai căng, thở ngắn, đầu nặng.','“Tất cả phải hoàn hảo và xong ngay.”','Nhảy giữa nhiều việc, bỏ ăn và nghỉ.','Có cảm giác đang rất bận và không bỏ sót việc.','Chất lượng giảm, kiệt sức tăng, càng khó ưu tiên.'],2,'Phân loại theo mức cần thiết và năng lượng'),
  research:[{org:'WHO',title:'Stress là phản ứng tự nhiên trước thách thức',summary:'WHO lưu ý stress ảnh hưởng cả tâm trí và cơ thể; thói quen hằng ngày và hỗ trợ xã hội có thể giúp quản lý.',url:'https://www.who.int/news-room/questions-and-answers/item/stress',source:'WHO · Stress'},{org:'WHO',title:'Kiệt sức nghề nghiệp liên quan công việc',summary:'WHO mô tả burnout qua kiệt quệ, xa cách tinh thần với công việc và hiệu quả nghề nghiệp giảm.',url:'https://www.who.int/standards/classifications/frequently-asked-questions/burn-out-an-occupational-phenomenon',source:'WHO · Burn-out'}],
  scenarios:[{icon:'01',context:'Đại học',situation:'Bài nhóm, thi và việc làm thêm cùng tuần.',autoThought:'“Mình phải làm hết, nếu không sẽ tụt lại.”',physicalResponse:'Vai căng, ngủ muộn.',typicalReaction:'Mở nhiều việc cùng lúc và không nghỉ.',healthierAlternative:'Đặt từng việc vào Must/Should/Can wait, xác định mức “đủ tốt” và nhờ nhóm nhận phần rõ ràng.'},{icon:'02',context:'Công việc',situation:'Bạn nhận thêm nhiệm vụ khi lịch đã đầy.',autoThought:'“Từ chối sẽ bị xem là không tận tâm.”',physicalResponse:'Đau đầu, thở gấp.',typicalReaction:'Đồng ý ngay rồi làm đêm.',healthierAlternative:'Đưa ra tải hiện tại và hỏi người giao việc muốn đổi ưu tiên nào.'}],
  practice:{type:'priority',title:'Ba quỹ đạo ưu tiên',description:'Đưa từng nhiệm vụ vào “Phải làm”, “Nên làm” hoặc “Có thể chờ”, rồi so khối lượng với năng lượng hiện có.',steps:[{label:'Gỡ khỏi đầu',instruction:'Viết mỗi nhiệm vụ trên một dòng.'},{label:'Xếp quỹ đạo',instruction:'Kéo hoặc dùng nút để chuyển nhiệm vụ.'},{label:'So năng lượng',instruction:'Chỉ cam kết khối lượng phù hợp hôm nay.'}]}
};

PLANET_DATA.saturn = {
  id:'saturn',name:'Sao Thổ',nameEn:'Saturn',emotion:'Trầm cảm',emotionEn:'Depression',texture:'saturn.png',
  tagline:'Khi mọi thứ trở nên nặng và xa, một hành động dưới hai phút vẫn là một chuyển động thật.',facts:epFacts('120.500 km','29,4 năm','274 (03/2025)','≈-140°C'),
  connection:{planetTraits:['Xa Mặt Trời và có sắc vàng lạnh','Hệ vành đai rộng tạo cảm giác chia lớp','Một năm kéo dài gần ba thập kỷ Trái Đất'],emotionTraits:['Năng lượng và hứng thú suy giảm','Cảm giác tách khỏi đời sống','Thời gian có thể trôi rất chậm và nặng'],analogy:'Sao Thổ đẹp nhưng xa, lạnh và được bao quanh bởi nhiều lớp vành đai. Trầm cảm cũng có thể tạo cảm giác đứng sau khoảng cách vô hình: thế giới vẫn đó nhưng khó chạm tới.',quote:{text:'Trong ngày rất tối, mục tiêu không phải tỏa sáng; mục tiêu có thể chỉ là giữ một điểm sáng nhỏ còn hoạt động.',author:'StellarMind'}},
  overview:{what:'Trầm cảm không chỉ là buồn. Nó có thể gồm tâm trạng thấp hoặc trống rỗng, mất hứng thú, thay đổi ngủ và ăn, mệt mỏi, khó tập trung và cảm giác vô vọng.',why:'Trầm cảm liên quan sự tương tác phức tạp giữa yếu tố sinh học, tâm lý và xã hội. Không có một nguyên nhân duy nhất và không phải lỗi của người trải nghiệm.',whenNormal:'Buồn và giảm năng lượng sau mất mát hay thất vọng là phản ứng con người. Chẩn đoán phụ thuộc thời gian, mức độ, nhóm triệu chứng và ảnh hưởng chức năng.',whenHarmful:'Nếu triệu chứng kéo dài, làm suy giảm sinh hoạt hoặc có ý nghĩ tự làm hại, hãy liên hệ chuyên gia, người đáng tin hoặc dịch vụ khẩn cấp địa phương ngay.',misconceptions:['Trầm cảm không phải lười biếng hay thiếu ý chí.','Một người vẫn đi học, đi làm và mỉm cười vẫn có thể đang cần hỗ trợ.']},
  signs:epSigns(
    [['Năng lượng rất thấp','Việc nhỏ như tắm hoặc ăn cũng cần nhiều sức.'],['Ngủ thay đổi','Ngủ quá ít, quá nhiều hoặc không hồi phục.'],['Cơ thể nặng','Chuyển động và lời nói có thể chậm hơn.']],
    [['Vô vọng','Tương lai bị nhìn như không thể thay đổi.'],['Tự trách','Đánh giá bản thân khắc nghiệt và tổng quát.'],['Khó tập trung','Đọc, quyết định hoặc nhớ việc trở nên khó.']],
    [['Mất hoạt động','Dừng những việc từng tạo niềm vui hoặc ý nghĩa.'],['Bỏ chăm sóc cơ bản','Ăn, vệ sinh và lịch trình bị gián đoạn.'],['Thu mình','Không trả lời vì không có năng lượng giải thích.']],
    [['Cảm thấy là gánh nặng','Khó tin rằng người khác thật sự muốn giúp.'],['Mất kết nối','Quan hệ giảm do im lặng kéo dài.'],['Che giấu','Dùng vẻ ổn để tránh làm người khác lo.']]
  ),
  bodyMap:[{x:50,y:26,label:'Đầu mờ và khó tập trung',size:'md'},{x:50,y:43,label:'Ngực nặng hoặc trống',size:'lg'},{x:37,y:62,label:'Tay chân chậm, ít năng lượng',size:'md'},{x:50,y:82,label:'Toàn thân nặng như tăng trọng lực',size:'lg'}],
  emotionalLoop:epLoop(['Một giai đoạn thất bại và mất nhịp sinh hoạt.','Mệt, nặng, ngủ không hồi phục.','“Làm gì cũng vô ích.”','Nằm lại, hủy kế hoạch và bỏ bữa.','Tránh được nỗ lực khi năng lượng quá thấp.','Ít trải nghiệm tích cực hơn, cảm giác bất lực mạnh hơn.'],3,'Chọn hành động dưới hai phút, không đòi động lực'),
  research:[{org:'WHO',title:'Trầm cảm có thể điều trị',summary:'WHO mô tả trầm cảm là rối loạn phổ biến, khác với thay đổi tâm trạng thông thường và có phương pháp điều trị hiệu quả.',url:'https://www.who.int/news-room/fact-sheets/detail/depression',source:'WHO · Depression'},{org:'NIMH',title:'Triệu chứng ảnh hưởng cảm xúc, suy nghĩ và hoạt động',summary:'NIMH cung cấp dấu hiệu, yếu tố nguy cơ và lựa chọn điều trị; đánh giá chuyên môn giúp phân biệt với tình trạng khác.',url:'https://www.nimh.nih.gov/health/topics/depression',source:'NIMH · Depression'}],
  scenarios:[{icon:'01',context:'Đại học',situation:'Bạn bỏ lỡ vài buổi học và bài tập bắt đầu dồn.',autoThought:'“Mình hỏng hết rồi, quay lại cũng vô ích.”',physicalResponse:'Cơ thể nặng, khó rời giường.',typicalReaction:'Tránh email và bỏ thêm buổi.',healthierAlternative:'Gửi một email hai câu cho cố vấn hoặc giảng viên và chọn một nhiệm vụ dưới hai phút để nối lại nhịp.'},{icon:'02',context:'Quan hệ',situation:'Bạn bè hỏi thăm nhưng bạn không đủ sức trò chuyện.',autoThought:'“Mình chỉ làm họ mệt.”',physicalResponse:'Ngực nặng, giọng nhỏ.',typicalReaction:'Không trả lời nhiều ngày.',healthierAlternative:'Gửi mẫu tin ngắn: “Mình đang ít năng lượng, chưa nói dài được nhưng cảm ơn bạn đã ở đây.”'}],
  crisis:true,
  practice:{type:'micro',title:'Thắp một điểm sáng cực nhỏ',description:'Chọn mức năng lượng thật, rồi nhận một hành động dưới hai phút thay vì đặt mục tiêu theo ngày khỏe nhất.',steps:[{label:'Đo năng lượng',instruction:'Không phán xét, chỉ chọn mức gần nhất.'},{label:'Chọn vi hành động',instruction:'Uống nước, mở rèm hoặc nhắn một câu đều được.'},{label:'Ghi nhận',instruction:'Hoàn thành nhỏ vẫn là dữ liệu rằng bạn có thể chuyển động.'}]}
};

PLANET_DATA.uranus = {
  id:'uranus',name:'Sao Thiên Vương',nameEn:'Uranus',emotion:'Tự ti',emotionEn:'Low self-worth',texture:'uranus.png',
  tagline:'Khác biệt không phải sai quỹ đạo; giá trị của bạn không cần được chứng minh bằng việc giống người khác.',facts:epFacts('50.724 km','84 năm','28','≈-195°C'),
  connection:{planetTraits:['Trục quay nghiêng gần như nằm ngang','Màu xanh lục lam khác biệt','Một mùa kéo dài hàng thập kỷ'],emotionTraits:['Cảm giác mình lệch chuẩn hoặc kém hơn','So sánh nét riêng với chuẩn của người khác','Bỏ qua thành tựu vì không thấy mình “đủ”'],analogy:'Sao Thiên Vương quay theo cách khác hẳn các hành tinh còn lại, nhưng sự khác biệt ấy là đặc tính chứ không phải khiếm khuyết. Tự ti thường biến khác biệt thành bản án thay vì dữ kiện trung tính.',quote:{text:'Bạn không cần thẳng theo trục của người khác để có một quỹ đạo hợp lệ.',author:'StellarMind'}},
  overview:{what:'Tự ti là cách đánh giá bản thân thấp, thường đi cùng so sánh, tự phê phán và nghi ngờ khả năng hoặc quyền được thuộc về.',why:'Não xây dựng hình ảnh bản thân từ trải nghiệm, phản hồi xã hội và tiêu chuẩn văn hóa. Thất bại hoặc lời phê bình dễ được ghi nhớ mạnh hơn thành công.',whenNormal:'Nghi ngờ bản thân trước việc mới có thể thúc đẩy học hỏi nếu nó cụ thể và không phủ định toàn bộ con người.',whenHarmful:'Khi tự ti khiến bạn né cơ hội, chấp nhận đối xử tệ, tự cô lập hoặc liên tục tự hạ thấp, việc nói chuyện với chuyên gia có thể hữu ích.',misconceptions:['Tự trọng không phải nghĩ mình hơn người khác.','Khiêm tốn không yêu cầu phủ nhận năng lực và nỗ lực của bản thân.']},
  signs:epSigns(
    [['Tư thế thu nhỏ','Vai co, mắt cúi khi thấy mình bị đánh giá.'],['Cổ họng nghẹn','Khó nói ý kiến hoặc nhận lời khen.'],['Mặt nóng','Xấu hổ và muốn biến mất khỏi sự chú ý.']],
    [['So sánh một chiều','So điểm yếu của mình với điểm nổi bật của người khác.'],['Phủ nhận thành công','Cho rằng kết quả tốt chỉ do may mắn.'],['Nhãn toàn thể','Một lỗi trở thành “mình vô dụng”.']],
    [['Né cơ hội','Không thử để tránh xác nhận nỗi sợ thất bại.'],['Xin lỗi quá mức','Xin lỗi cả khi mình không gây lỗi.'],['Làm hài lòng','Bỏ nhu cầu cá nhân để được chấp nhận.']],
    [['Khó nhận lời khen','Phản bác hoặc giảm nhẹ sự ghi nhận.'],['Ngại đóng góp','Giữ im lặng dù có ý tưởng.'],['Chấp nhận ít hơn','Tin rằng mình không xứng đáng với ranh giới tốt.']]
  ),
  bodyMap:[{x:50,y:27,label:'Mặt nóng khi bị chú ý',size:'md'},{x:50,y:36,label:'Cổ họng nghẹn, khó nói',size:'lg'},{x:45,y:48,label:'Vai co và tư thế thu nhỏ',size:'md'},{x:50,y:67,label:'Bụng chìm khi so sánh',size:'md'}],
  emotionalLoop:epLoop(['Thấy bạn cùng tuổi công bố một thành tựu lớn.','Bụng chìm, mặt nóng, vai co.','“Ai cũng tiến lên, chỉ mình kém cỏi.”','Đóng ứng dụng và bỏ kế hoạch đang làm.','Tránh cảm giác bị so sánh thêm.','Ít dữ kiện về năng lực, niềm tin “không đủ” mạnh hơn.'],2,'Tách dữ kiện khỏi nhãn đánh giá'),
  research:[{org:'APA Dictionary',title:'Self-esteem là đánh giá về bản thân',summary:'Khái niệm này liên quan cách cá nhân nhìn nhận giá trị và năng lực, không đồng nhất với một thành tích đơn lẻ.',url:'https://dictionary.apa.org/self-esteem',source:'APA Dictionary · Self-esteem'},{org:'PubMed',title:'Self-compassion và đau khổ tâm lý',summary:'Tổng quan hệ thống cho thấy self-compassion có liên hệ với mức đau khổ thấp hơn; bối cảnh nghiên cứu vẫn cần được xem xét.',url:'https://pubmed.ncbi.nlm.nih.gov/34955971/',source:'PubMed · Systematic review'}],
  scenarios:[{icon:'01',context:'Công việc',situation:'Đồng nghiệp được khen trong cuộc họp.',autoThought:'“Mình chẳng đóng góp gì đáng kể.”',physicalResponse:'Vai co, mắt nhìn xuống.',typicalReaction:'Không đề xuất ý tưởng ở phần sau.',healthierAlternative:'Ghi dữ kiện về phần mình đã làm và đóng góp một ý cụ thể thay vì đòi cảm giác tự tin hoàn hảo.'},{icon:'02',context:'Mạng xã hội',situation:'Bạn thấy ảnh chỉnh chu của người khác.',autoThought:'“Mình không thú vị và không đẹp bằng.”',physicalResponse:'Bụng chìm, mặt nóng.',typicalReaction:'So sánh lâu hơn hoặc xóa bài của mình.',healthierAlternative:'Nhắc rằng đang so hậu trường với sản phẩm chọn lọc; ghi một phẩm chất và một nỗ lực không liên quan ngoại hình.'}],
  practice:{type:'reframe',title:'Lăng kính kiểm chứng giá trị',description:'Biến câu tự phê phán thành giả thuyết có thể kiểm tra, rồi thu thập bằng chứng hai phía và ghi nhận thành tựu nhỏ.',steps:[{label:'Bắt câu phán xét',instruction:'Viết đúng câu đang chạy trong đầu.'},{label:'Kiểm chứng',instruction:'Tìm dữ kiện ủng hộ và phản bác.'},{label:'Ghi nhận',instruction:'Lưu một việc bạn đã hoàn thành hoặc đã cố gắng.'}]}
};

PLANET_DATA.neptune = {
  id:'neptune',name:'Sao Hải Vương',nameEn:'Neptune',emotion:'Mất phương hướng',emotionEn:'Disorientation',texture:'neptune.png',
  tagline:'Khi chưa thấy đường dài, một giá trị rõ và một thử nghiệm nhỏ có thể trở thành la bàn.',facts:epFacts('49.244 km','164,8 năm','16','≈-200°C'),
  connection:{planetTraits:['Hành tinh xa nhất trong tám hành tinh','Gió nhanh và khí quyển xanh sâu','Mỗi mùa kéo dài hơn bốn thập kỷ'],emotionTraits:['Khó thấy mục tiêu và tiêu chí lựa chọn','Nhiều khả năng tạo thành sương mù','Dễ đứng yên vì muốn câu trả lời chắc chắn'],analogy:'Sao Hải Vương ở rất xa, nơi ánh sáng yếu và khí quyển chuyển động dữ dội. Mất phương hướng giống điều hướng trong sương: không thiếu lựa chọn, mà thiếu một điểm tham chiếu đủ rõ cho bước kế tiếp.',quote:{text:'La bàn không cho bạn toàn bộ bản đồ; nó chỉ giúp chọn hướng cho bước tiếp theo.',author:'StellarMind'}},
  overview:{what:'Mất phương hướng là trạng thái khó xác định điều mình muốn, ưu tiên hoặc bước tiếp theo. Nó thường xuất hiện sau thay đổi lớn, mất vai trò hoặc khi có quá nhiều lựa chọn.',why:'Não cần tiêu chí để ra quyết định. Khi giá trị xung đột, thông tin quá tải hoặc tương lai không chắc chắn, hệ thống quyết định dễ bị đóng băng.',whenNormal:'Giai đoạn chuyển trường, đổi nghề, kết thúc quan hệ hoặc bước sang vai trò mới thường cần thời gian khám phá lại.',whenHarmful:'Nếu cảm giác lạc hướng kéo dài cùng tuyệt vọng, tê liệt, mất chức năng hoặc triệu chứng sức khỏe tâm thần khác, hãy tìm hỗ trợ chuyên môn.',misconceptions:['Không biết ngay con đường dài hạn không có nghĩa là bạn thất bại.','Mục tiêu thường được khám phá qua thử nghiệm, không chỉ qua suy nghĩ.']},
  signs:epSigns(
    [['Đầu mờ','Khó giữ thông tin và so sánh lựa chọn.'],['Cơ thể trì trệ','Năng lượng bị giữ lại vì chưa biết hướng.'],['Bồn chồn nền','Muốn đi đâu đó nhưng không biết bắt đầu đâu.']],
    [['Quá nhiều khả năng','Mỗi lựa chọn mở thêm nhiều nhánh.'],['Đòi quyết định hoàn hảo','Sợ một lựa chọn sẽ khóa toàn bộ tương lai.'],['Mất tiêu chí','Khó phân biệt điều mình muốn với kỳ vọng.']],
    [['Nghiên cứu vô tận','Thu thập thêm thông tin nhưng không thử.'],['Đổi hướng liên tục','Bỏ kế hoạch trước khi có đủ dữ liệu.'],['Để người khác quyết','Chọn theo tiếng nói mạnh nhất quanh mình.']],
    [['So bản đồ đời người khác','Dùng tiến độ của họ để đánh giá đường của mình.'],['Khó cam kết','Sợ nói mục tiêu rồi phải giữ mãi.'],['Thu mình','Ngại giải thích rằng mình chưa có câu trả lời.']]
  ),
  bodyMap:[{x:50,y:25,label:'Đầu mờ và quá tải lựa chọn',size:'lg'},{x:50,y:43,label:'Ngực không rõ muốn tiến hay lùi',size:'md'},{x:50,y:64,label:'Bụng bồn chồn trước quyết định',size:'md'},{x:48,y:82,label:'Chân đứng yên vì chưa có hướng hoàn hảo',size:'lg'}],
  emotionalLoop:epLoop(['Sắp tốt nghiệp nhưng chưa biết chọn nghề nào.','Đầu mờ, bụng bồn chồn, khó ngủ.','“Nếu chọn sai, mình sẽ phá hỏng tương lai.”','Đọc thêm hàng chục lựa chọn nhưng không thử cái nào.','Tránh rủi ro phải cam kết.','Không có dữ liệu trải nghiệm, sương mù dày hơn.'],3,'Chọn thử nghiệm nhỏ có thể đảo ngược'),
  research:[{org:'APA',title:'Giá trị giúp tổ chức lựa chọn',summary:'Trong các tiếp cận dựa trên giá trị, hành động có ý nghĩa không đòi loại bỏ hoàn toàn sự không chắc chắn trước.',url:'https://www.apa.org/ptsd-guideline/patients-and-families/cognitive-behavioral',source:'APA · Behavioral approaches'},{org:'PubMed',title:'Ý nghĩa trong cuộc sống và sức khỏe tâm lý',summary:'Nghiên cứu phân biệt sự hiện diện của ý nghĩa và quá trình tìm kiếm ý nghĩa; bối cảnh quyết định mối liên hệ với sức khỏe.',url:'https://pubmed.ncbi.nlm.nih.gov/27929687/',source:'PubMed · Meaning in life'}],
  scenarios:[{icon:'01',context:'Sau tốt nghiệp',situation:'Bạn có ba hướng nghề nghiệp nhưng chưa từng trải nghiệm thực tế.',autoThought:'“Phải chọn đúng một lần cho cả đời.”',physicalResponse:'Đầu mờ, mất ngủ.',typicalReaction:'Xem thêm tư vấn nhưng không nộp đâu.',healthierAlternative:'Chọn một giá trị, phỏng vấn người trong nghề và thử dự án 10 giờ trước khi đánh giá tiếp.'},{icon:'02',context:'Mối quan hệ',situation:'Bạn không biết nên tiếp tục hay kết thúc.',autoThought:'“Mình phải chắc chắn 100% rồi mới nói.”',physicalResponse:'Ngực căng, bụng bồn chồn.',typicalReaction:'Tránh cuộc trò chuyện và để tình trạng kéo dài.',healthierAlternative:'Xác định ba giá trị quan hệ, ghi dữ kiện hiện tại và đặt cuộc nói chuyện có phạm vi rõ.'}],
  practice:{type:'compass',title:'La bàn ba giá trị',description:'Chọn ba giá trị làm tiêu chí, rồi thiết kế thử nghiệm nhỏ để thu dữ liệu thay vì chờ sự chắc chắn tuyệt đối.',steps:[{label:'Chọn giá trị',instruction:'Chọn điều quan trọng ở giai đoạn hiện tại.'},{label:'Thiết kế thử nghiệm',instruction:'Nhỏ, ít rủi ro và có thể hoàn thành.'},{label:'Hẹn ngày xem lại',instruction:'Đánh giá điều đã học thay vì chỉ hỏi đúng hay sai.'}]}
};
